# Generated by Django 3.0.5 on 2020-05-15 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20200515_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='index.jpg', upload_to='profile_pics'),
        ),
    ]
