# Generated by Django 3.0.6 on 2020-05-23 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20200516_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='index.jpg', upload_to='profile_pics'),
        ),
    ]
