# Generated by Django 3.0.5 on 2020-04-25 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0003_auto_20200416_1853'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'verbose_name_plural': 'Entries'},
        ),
    ]
