# Generated by Django 3.0.5 on 2020-04-27 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0004_auto_20200425_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='last_updated',
            field=models.DateField(blank=True, null=True),
        ),
    ]
