# Generated by Django 3.0.5 on 2020-04-28 02:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0005_auto_20200428_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='last_updated',
            field=models.DateField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
