# Generated by Django 3.0.5 on 2020-05-03 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0007_auto_20200503_1133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='slug',
        ),
        migrations.AddField(
            model_name='entry',
            name='slug',
            field=models.SlugField(blank=True, max_length=150),
        ),
    ]
