# Generated by Django 3.0.5 on 2020-05-03 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0008_auto_20200503_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='slug',
            field=models.SlugField(blank=True, max_length=150),
        ),
    ]
